# Generated by Django 4.2.11 on 2024-04-25 03:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameroom_room_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('box1', models.CharField(max_length=1, null=True)),
                ('box2', models.CharField(max_length=1, null=True)),
                ('box3', models.CharField(max_length=1, null=True)),
                ('box4', models.CharField(max_length=1, null=True)),
                ('box5', models.CharField(max_length=1, null=True)),
                ('box6', models.CharField(max_length=1, null=True)),
                ('box7', models.CharField(max_length=1, null=True)),
                ('box8', models.CharField(max_length=1, null=True)),
                ('box9', models.CharField(max_length=1, null=True)),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_room', to='game.gameroom')),
            ],
        ),
    ]
