# Generated by Django 4.2.11 on 2024-04-25 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
